



[package]
name = "erc20-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
erc20 = { path = "../app" }

[build-dependencies]
gwasm-builder.workspace = true
sails-idlgen.workspace = true
erc20 = { path = "../app" }
